// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXKyBdNEDrwU_8NtiUMek-6ENubeODLl0',
    appId: '1:2534597503:web:5f9dc781be8b434ead304a',
    messagingSenderId: '2534597503',
    projectId: 'sims-c73f6',
    authDomain: 'sims-c73f6.firebaseapp.com',
    storageBucket: 'sims-c73f6.appspot.com',
    measurementId: 'G-7M7MF0LQXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6DeA1klk-AiA_evymztjzd1I2m--zLzg',
    appId: '1:2534597503:android:a2478c10ca92589fad304a',
    messagingSenderId: '2534597503',
    projectId: 'sims-c73f6',
    storageBucket: 'sims-c73f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1T5nq0h3L0jyDdFFZsWJtHhsjr5mcVMY',
    appId: '1:2534597503:ios:ea21fc026b09c2cdad304a',
    messagingSenderId: '2534597503',
    projectId: 'sims-c73f6',
    storageBucket: 'sims-c73f6.appspot.com',
    iosClientId: '2534597503-r027vg08rh9raglu6vnqcd4qu2j1guhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sims',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1T5nq0h3L0jyDdFFZsWJtHhsjr5mcVMY',
    appId: '1:2534597503:ios:ea21fc026b09c2cdad304a',
    messagingSenderId: '2534597503',
    projectId: 'sims-c73f6',
    storageBucket: 'sims-c73f6.appspot.com',
    iosClientId: '2534597503-r027vg08rh9raglu6vnqcd4qu2j1guhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sims',
  );
}
